pool:
  vmImage: 'windows-2019'

steps:
- script: |
    npm install abaplint -g
  displayName: 'abaplint Install'
- script: |
    abaplint --version
  displayName: 'abaplint Version'
- script: |
    abaplint -f standard --outformat junit --outfile report.xml "src/**/*.*"
  displayName: 'abaplint Run'
- task: PublishTestResults@1
  inputs:
    testRunner: 'JUnit'
    testResultsFiles: 'report.xml' 
